version: "3.9" # optional since v1.27.0
services:
  db:
    image: "mongo"
    container_name: "white-hat_db"
    ports:
      - "27017:27017"
    restart: "always"
    command: "mongod --quiet --logpath /dev/null"

  api:
    container_name: "white-hat_api"
    build: .
    ports:
      - "1323:1323"
    depends_on:
      - "db"
    links:
      - "db"
