version: "3.9"

services:
  api:
    build: .
    container_name: api
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - database
    links:
      - database

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongov:/data/mongo
    command: --quiet

volumes:
  mongov:
    driver: local
